### ISSUE TITLE
Functions in selectors

### ISSUE THREAD

**Issue by AlexWayfer** [andyjansson/postcss-functions#36]
Hello.

I have such functions:

```js
function headings(from = 1, to = 6) {
	[...Array(to + 1).keys()].slice(from).map(number => `h${number}`).join(', ')
}
```

And trying to use them in this way:

```pcss
headings() {
	text-align: center;
}
```

But getting:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.32, but postcss-functions uses 6.0.23. Perhaps this is the source of the error below.
TypeError: func.apply is not a function
```

**Comment by andyjansson** [comment]
How are you registering your function?

**Comment by AlexWayfer** [comment]
> How are you registering your function?

```
require('postcss-functions')({
	glob: `${__dirname}/assets/scripts/postcss-functions/*.js`
})
```

`assets/scripts/postcss-functions/headings.js`

**Comment by andyjansson** [comment]
Is your function the default export of that file?

**Comment by AlexWayfer** [comment]
> Is your function the default export of that file?

No, it was not.

So, I've tried to add `export default`, also splitted one file with 2 functions into 2 files.

But I can't reuse one of them into another:


```js
import inputsWithTypes from 'inputsWithTypes'

export default function allHorizontalInputs() {
	return inputsWithTypes(
		'text', 'email', 'password', 'number', 'url', 'search', 'date', 'time', 'file'
	)
}
```

```
/home/alex/Projects/ruby/test/foo_bar/assets/scripts/postcss-functions/all-horizontal-inputs.js:1
import inputsWithTypes from 'inputsWithTypes'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1167:16)
    at Module._compile (internal/modules/cjs/loader.js:1215:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at /home/alex/Projects/ruby/test/foo_bar/node_modules/postcss-functions/dist/index.js:36:22
    at Array.forEach (<anonymous>)
    at /home/alex/Projects/ruby/test/foo_bar/node_modules/postcss-functions/dist/index.js:34:32
```

**Comment by andyjansson** [comment]
Glad that fixed your issue. The problem you're facing now however is unrelated to the plugin. I believe you need to look into ECMAScript modules. Good luck.
